name: Python Template Sync

on:
  push:
    paths:
      - '.github/workflows/template-sync.yaml'
  schedule:
    - cron: "0 5 * * 1" # Weekly Monday 06:00 Europe/Amsterdam (05:00 UTC in winter)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: schubergphilis-ep/github-python-workflows/.github/workflows/template-sync.yaml@v1.0.0
    with:
      project_description: 'python library for testing'
      project_name: 'test260211lib'
      project_slug: 'test260211lib'
    secrets: inherit
